fix(android): support rn version 0.68 (#2193)
Upgrading react-native-image-picker from 5.4.2 to 5.5.0 resulted in my app no longer building because of the following issue: `error: cannot find symbol new ImagePickerPackage()`

This issue was introduced here: 
https://github.com/react-native-image-picker/react-native-image-picker/commit/4584d7b0df4b859a73fc70aa2f17ba643885427f

My stack: 
Using react-native 0.68.2
Gradle 7.3.1
buildToolsVersion 33
compileSdkVersion 33
targetSdkVersion 33
minSdkVersion 24
kotlinVersion 1.7.0